language: perl

perl:
  - "5.18"

sudo: required

dist: trusty

#install:
#  - perl Makefile.PL
#  - make test

addons:
  apt:
    packages:
      - cpanminus
      - libmodule-install-perl
      - libxml-libxml-perl
      - libcapture-tiny-perl
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-fonts-extra
      - texlive-extra-utils
